# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZc4yKtSvnoGCAhVQs0fK9_TRWGPufA5

## **E**xtract

Extraia a lista de IDs de usuário a partir do arquivo CSV. Para cada ID, faça uma requisição GET para obter os dados do usuário correspondente.
"""

import pandas as pd

df = pd.read_csv('SDW2023.csv')
user_ids = df['UserID'].tolist()
print(user_ids)

import json

users = pd.read_csv('SDW2023.csv').to_dict(orient='records')

print(json.dumps(users, indent=2))

"""## **T**ransform

Utilize a API do OpenAI GPT-4 para gerar uma mensagem de marketing personalizada para cada usuário.
"""

!pip install openai

import os
os.environ["OPENAI_API_KEY"] = "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"

from openai import OpenAI

client = OpenAI()

def generate_ai_news(user):
    response = client.responses.create(
        model="gpt-4.1-mini",
        #input=f"Crie uma mensagem para {user['name']} sobre a importância dos investimentos (máximo de 100 caracteres)."
        input=f"Crie uma mensagem para {user['name']} sobre a importância das bananas (máximo de 100 caracteres)."
    )
    return response.output_text

for user in users:
    news = generate_ai_news(user)
    print(news)

"""## **L**oad

Atualize a lista de "news" de cada usuário na API com a nova mensagem gerada.
"""

import csv

# 1️⃣ Lê o CSV inteiro
with open("SDW2023.csv", newline="", encoding="utf-8") as f:
    rows = list(csv.DictReader(f))

# 2️⃣ Preenche a coluna news
for row in rows:
    user = {"name": row["name"]}
    row["news"] = generate_ai_news(user)

# 3️⃣ Reescreve o CSV
with open("SDW2023.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)

with open("SDW2023.csv", newline="", encoding="utf-8") as f:
    rows = list(csv.DictReader(f))

# transforma em JSON (string)
json_data = json.dumps(rows, indent=2, ensure_ascii=False)

# mostra no terminal
print(json_data)